### ISSUE TITLE
Different colors inside Tmux, using Neovim

### ISSUE THREAD

**Issue by taq** [dikiaap/minimalist#3]
Hi, I'm having some issues running the colorscheme inside Tmux, using Neovim. The orange keywords turns to orange background, do you have some clue about this? Thanks!

![inside_tmux](https://cloud.githubusercontent.com/assets/9789/21641001/11e6d5d0-d260-11e6-92b8-b338180fba6f.jpg)
![out_tmux](https://cloud.githubusercontent.com/assets/9789/21641002/11e7d804-d260-11e6-9bfd-8e45238d141d.jpg)

**Comment by dikiaap** [comment]
@taq Hi there,
I was checking my code and there's no settings with orange background.
Maybe you use some syntax highlighting plugins that can override some colorscheme.
Also try update this colorscheme. :)

**Comment by taq** [comment]
Hey @dikiaap !

Yeah, that's because I think its weird to have orange background. I just upgraded all my plugins before sending your this issue, but as I said, it only happens when I run it inside of Tmux, with Neovim. Regular Vim seems fine (but I don't have italics there), did you already run your colorscheme with Neovim, inside of Tmux? Don't you have similar results?

**Comment by taq** [comment]
I just run Neovim with the option `--noplugin` to avoid load the plugins and just changed the colorscheme, the orange background is still there. :-)

**Comment by dikiaap** [comment]
I already run the colorscheme inside of tmux with neovim. It works over here.

**Comment by taq** [comment]
Ok, nevermind.
