### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by ErikWallstrom** [dikiaap/minimalist#4]
Hey, I really like this theme. One thing that is missing though, is transparent background in my opinion. What should I do to get a custom background?

**Comment by dikiaap** [comment]
Thank you! You could use compton to get transparent background. I've tried it once and it works well.

**Comment by ErikWallstrom** [comment]
@dikiaap 
[Jellybeans color scheme](https://github.com/nanotech/jellybeans.vim) allows you to override the background color like this:

```
let g:jellybeans_overrides = {
\    'background': { 'guibg': '000000' },
\}
```

This makes the theme use the background color the user had as background for their terminal before they started vim. Would this be possible to implement?

**Comment by dikiaap** [comment]
Yeah, I guess so. You can also override in .vimrc like `hi Normal ctermbg=NONE guibg=NONE`

**Comment by ErikWallstrom** [comment]
@dikiaap Oh, that was easy. I feel stupid now. Thanks a lot! 

By the way, comments are quite hard to see because of their color. I guess that's by design, but I'd make them at least a bit brighter

**Comment by dikiaap** [comment]
@ErikWallstrom Great.

That's all syntax highlighting I take from material-theme and I liken it.
<p align="center">
<img src="https://cloud.githubusercontent.com/assets/8542502/26271153/641817c4-3d2c-11e7-87cc-6038025ce197.png" width="600px">
</p>
