### ISSUE TITLE
Mixed Colors

### ISSUE THREAD

**Issue by SethGower** [dikiaap/minimalist#5]
I am not sure the reason that this is happening, but I am getting a weird color mixing at the ends of lines. I think that it has to do with end of line characters, because when I put a character at the end of the line and delete it, the color mixing goes away for that line. I am using this in conjunction with the [Arc-Dark](https://github.com/horst3180/arc-theme) Gnome 3 theme.
![screenshot_1](https://user-images.githubusercontent.com/19225089/34586370-bc240c80-f171-11e7-8011-980bbfea1ecb.png)

**Comment by dikiaap** [comment]
Have you tested it in another terminal? And make sure your vim is updated to a newer version. https://launchpad.net/~jonathonf/+archive/ubuntu/vim

**Comment by SethGower** [comment]
No, I have just tested it on the normal ubuntu gnome terminal.

**Comment by SethGower** [comment]
OK, it works properly with xterm, but I also haven't customized the colorscheme of xterm. 
Doesn't work in Terminator.
Konsole works
Tilda Doesn't
Yakuake works

**Comment by dikiaap** [comment]
I am using Ubuntu 16.04 LTS. I just tested it with LXTerminal, GNOME Terminal, Terminator, xterm and it's fine here. Could you post what's your distro version, vim/neovim version and your .vimrc config?

![screenshot from 2018-01-06 22-44-35](https://user-images.githubusercontent.com/8542502/34641215-3ec336a8-f333-11e7-8817-e0299b738aa2.png)
> Terminator with [base16-solarized](https://github.com/chriskempson/base16-shell) colorscheme.

![screenshot from 2018-01-06 22-49-44](https://user-images.githubusercontent.com/8542502/34641297-6bfa4caa-f334-11e7-99ea-69c4837ef74f.png)
> GNOME Terminal with [base16-solarized](https://github.com/chriskempson/base16-shell) colorscheme.

You can try another vim colorscheme too. If the problem still there, it's probably your custom terminal colorscheme has conflict with vim colorschemes.

Or with a trick that maybe a bit cruel by changing the background of terminal same as background in vim colorscheme.

**Comment by SethGower** [comment]
I am running Ubuntu Gnome 17.04 and using Vim version 8.0. 
[this](https://gist.github.com/SethGower/c42a9f59b79918e6d2fd179a6d6165a1) is the output of `vim --version`
[this](https://gist.github.com/SethGower/6258e555ea9044c22f85f8559c5c6583) is my `.vimrc`

And I realize this isn't really a minimalist problem, but I get [this](https://gist.github.com/SethGower/f04c353c411f5bcf87f1c212bb811064) error when I run `. ./.vimrc`.

**Comment by dikiaap** [comment]
Okay. So, I am using your config on my PC and it looks good here.
But when I test your config and mine on my phone and I enable and also disable minimalist colorscheme, I have a problem like yours as you mentioned above.
This is similar with your problem I guess. Both configs has glitch in background like that. Although I'm using neovim without colorscheme. I assume this is a issue in vim.

![Glitch](http://telegra.ph/file/457d3c439e0da6fba6223.png)

**Comment by dikiaap** [comment]
My understanding was the colorshceme is not working properly in some Terminal. Since there's no response, I think I'm going to close this.
